#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
地图格式转换工具

功能：
1. PGM <-> PNG 格式互转
2. 生成测试地图
3. 上传地图到配置服务器
4. 从ROS地图文件转换

用法：
  python3 map_converter.py pgm2png input.pgm output.png
  python3 map_converter.py png2pgm input.png output.pgm
  python3 map_converter.py generate test_map.png --width 600 --height 400
  python3 map_converter.py upload slam_map.png --server http://localhost:8080
"""

import argparse
import struct
import sys
from pathlib import Path

try:
    from PIL import Image
    import numpy as np
    HAS_PIL = True
except ImportError:
    HAS_PIL = False
    print("警告: 未安装PIL/Pillow，部分功能不可用")
    print("安装: pip install Pillow numpy")

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False


def read_pgm(filename):
    """读取PGM文件"""
    with open(filename, 'rb') as f:
        # 读取魔数
        magic = f.readline().strip()
        if magic not in [b'P5', b'P2']:
            raise ValueError(f"不支持的PGM格式: {magic}")
        
        # 跳过注释行
        while True:
            line = f.readline()
            if not line.startswith(b'#'):
                break
        
        # 读取宽度和高度
        width, height = map(int, line.split())
        
        # 读取最大灰度值
        maxval = int(f.readline().strip())
        
        # 读取像素数据
        if magic == b'P5':
            # 二进制格式
            data = f.read()
            pixels = list(data)
        else:
            # ASCII格式
            data = f.read().decode('ascii')
            pixels = [int(x) for x in data.split()]
        
        return width, height, maxval, pixels


def write_pgm(filename, width, height, pixels, maxval=255):
    """写入PGM文件"""
    with open(filename, 'wb') as f:
        # 写入头部
        header = f"P5\n# Generated by map_converter.py\n{width} {height}\n{maxval}\n"
        f.write(header.encode('ascii'))
        # 写入像素数据
        f.write(bytes(pixels))
    print(f"✓ 已保存PGM文件: {filename} ({width}x{height})")


def pgm_to_png(pgm_file, png_file):
    """PGM转PNG"""
    if not HAS_PIL:
        print("错误: 需要安装Pillow库")
        return False
    
    width, height, maxval, pixels = read_pgm(pgm_file)
    
    # 转换为numpy数组
    img_array = np.array(pixels, dtype=np.uint8).reshape((height, width))
    
    # 创建PIL图像
    img = Image.fromarray(img_array, mode='L')
    img.save(png_file)
    
    print(f"✓ 已转换: {pgm_file} -> {png_file}")
    print(f"  尺寸: {width}x{height}, 最大值: {maxval}")
    return True


def png_to_pgm(png_file, pgm_file):
    """PNG转PGM"""
    if not HAS_PIL:
        print("错误: 需要安装Pillow库")
        return False
    
    # 读取PNG
    img = Image.open(png_file)
    
    # 转换为灰度
    if img.mode != 'L':
        img = img.convert('L')
    
    width, height = img.size
    pixels = list(img.getdata())
    
    # 写入PGM
    write_pgm(pgm_file, width, height, pixels)
    
    print(f"✓ 已转换: {png_file} -> {pgm_file}")
    return True


def generate_test_map(output_file, width=600, height=400, format='png'):
    """生成测试地图"""
    if not HAS_PIL:
        print("错误: 需要安装Pillow库")
        return False
    
    print(f"生成测试地图 {width}x{height}...")
    
    # 创建地图数组
    map_data = np.ones((height, width), dtype=np.uint8) * 240  # 白色背景（自由空间）
    
    # 添加外墙（黑色）
    border = 10
    map_data[0:border, :] = 20
    map_data[height-border:height, :] = 20
    map_data[:, 0:border] = 20
    map_data[:, width-border:width] = 20
    
    # 添加一些房间隔墙
    # 垂直墙
    map_data[100:300, 200:210] = 20
    map_data[100:300, 400:410] = 20
    
    # 水平墙
    map_data[100:110, 200:400] = 20
    map_data[290:300, 200:400] = 20
    
    # 添加一些障碍物
    map_data[150:180, 250:280] = 20
    map_data[220:250, 320:350] = 20
    
    # 添加未知区域（灰色）
    map_data[50:80, 450:550] = 128
    
    # 保存
    img = Image.fromarray(map_data, mode='L')
    
    if format == 'png' or output_file.endswith('.png'):
        img.save(output_file, 'PNG')
    elif format == 'pgm' or output_file.endswith('.pgm'):
        pixels = list(img.getdata())
        write_pgm(output_file, width, height, pixels)
    else:
        img.save(output_file)
    
    print(f"✓ 已生成测试地图: {output_file}")
    print(f"  尺寸: {width}x{height}")
    print(f"  包含: 外墙、房间、障碍物、未知区域")
    return True


def upload_map(map_file, server_url):
    """上传地图到配置服务器"""
    if not HAS_REQUESTS:
        print("错误: 需要安装requests库")
        print("安装: pip install requests")
        return False
    
    # 确定Content-Type
    if map_file.endswith('.pgm'):
        content_type = 'image/pgm'
    elif map_file.endswith('.png'):
        content_type = 'image/png'
    else:
        print(f"警告: 未知文件类型，使用 image/png")
        content_type = 'image/png'
    
    # 读取文件
    with open(map_file, 'rb') as f:
        map_data = f.read()
    
    # 上传
    url = f"{server_url}/api/upload_map"
    print(f"上传地图到: {url}")
    print(f"  文件: {map_file} ({len(map_data)} bytes)")
    print(f"  类型: {content_type}")
    
    try:
        response = requests.post(
            url,
            data=map_data,
            headers={'Content-Type': content_type},
            timeout=10
        )
        
        if response.status_code == 200:
            print(f"✓ 上传成功: {response.json()}")
            return True
        else:
            print(f"✗ 上传失败: HTTP {response.status_code}")
            print(f"  响应: {response.text}")
            return False
    except Exception as e:
        print(f"✗ 上传失败: {e}")
        return False


def convert_ros_map(yaml_file, output_file):
    """从ROS地图YAML文件转换"""
    import yaml
    
    yaml_path = Path(yaml_file)
    if not yaml_path.exists():
        print(f"错误: 文件不存在: {yaml_file}")
        return False
    
    # 读取YAML
    with open(yaml_file, 'r') as f:
        map_info = yaml.safe_load(f)
    
    # 获取地图图像文件
    image_file = map_info.get('image', '')
    if not Path(image_file).is_absolute():
        image_file = yaml_path.parent / image_file
    
    if not Path(image_file).exists():
        print(f"错误: 地图图像文件不存在: {image_file}")
        return False
    
    print(f"ROS地图信息:")
    print(f"  图像: {image_file}")
    print(f"  分辨率: {map_info.get('resolution', 'N/A')} m/pixel")
    print(f"  原点: {map_info.get('origin', 'N/A')}")
    
    # 转换格式
    if output_file.endswith('.png'):
        if str(image_file).endswith('.pgm'):
            return pgm_to_png(str(image_file), output_file)
        else:
            # 直接复制
            import shutil
            shutil.copy(image_file, output_file)
            print(f"✓ 已复制: {image_file} -> {output_file}")
            return True
    elif output_file.endswith('.pgm'):
        if str(image_file).endswith('.png'):
            return png_to_pgm(str(image_file), output_file)
        else:
            import shutil
            shutil.copy(image_file, output_file)
            print(f"✓ 已复制: {image_file} -> {output_file}")
            return True


def main():
    parser = argparse.ArgumentParser(
        description='地图格式转换工具',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  # PGM转PNG
  python3 map_converter.py pgm2png input.pgm output.png
  
  # PNG转PGM
  python3 map_converter.py png2pgm input.png output.pgm
  
  # 生成测试地图
  python3 map_converter.py generate test_map.png --width 600 --height 400
  
  # 上传地图
  python3 map_converter.py upload slam_map.png --server http://localhost:8080
  
  # 从ROS地图转换
  python3 map_converter.py ros my_map.yaml output.png
        """
    )
    
    subparsers = parser.add_subparsers(dest='command', help='命令')
    
    # pgm2png
    p1 = subparsers.add_parser('pgm2png', help='PGM转PNG')
    p1.add_argument('input', help='输入PGM文件')
    p1.add_argument('output', help='输出PNG文件')
    
    # png2pgm
    p2 = subparsers.add_parser('png2pgm', help='PNG转PGM')
    p2.add_argument('input', help='输入PNG文件')
    p2.add_argument('output', help='输出PGM文件')
    
    # generate
    p3 = subparsers.add_parser('generate', help='生成测试地图')
    p3.add_argument('output', help='输出文件')
    p3.add_argument('--width', type=int, default=600, help='宽度（默认600）')
    p3.add_argument('--height', type=int, default=400, help='高度（默认400）')
    p3.add_argument('--format', choices=['png', 'pgm'], help='格式（自动检测）')
    
    # upload
    p4 = subparsers.add_parser('upload', help='上传地图到服务器')
    p4.add_argument('file', help='地图文件')
    p4.add_argument('--server', default='http://localhost:8080', help='服务器地址')
    
    # ros
    p5 = subparsers.add_parser('ros', help='从ROS地图转换')
    p5.add_argument('yaml', help='ROS地图YAML文件')
    p5.add_argument('output', help='输出文件')
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        return
    
    # 执行命令
    if args.command == 'pgm2png':
        pgm_to_png(args.input, args.output)
    elif args.command == 'png2pgm':
        png_to_pgm(args.input, args.output)
    elif args.command == 'generate':
        generate_test_map(args.output, args.width, args.height, args.format)
    elif args.command == 'upload':
        upload_map(args.file, args.server)
    elif args.command == 'ros':
        convert_ros_map(args.yaml, args.output)


if __name__ == '__main__':
    main()
